// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"database/sql"
)

type Account struct {
	ID            int64  `json:"id"`
	PlayerCode    string `json:"player_code"`
	FullUsername  string `json:"full_username"`
	DisplayName   string `json:"display_name"`
	PinHash       string `json:"pin_hash"`
	MemberStatus  string `json:"member_status"`
	AccountStatus string `json:"account_status"`
	MustChangePin int64  `json:"must_change_pin"`
	CreatedAtUtc  int64  `json:"created_at_utc"`
}

type AdminSession struct {
	ID           int64  `json:"id"`
	TokenHash    []byte `json:"token_hash"`
	CsrfSecret   []byte `json:"csrf_secret"`
	CreatedAtUtc int64  `json:"created_at_utc"`
	ExpiresAtUtc int64  `json:"expires_at_utc"`
}

type AttendancePlan struct {
	ID             int64  `json:"id"`
	AccountID      int64  `json:"account_id"`
	AttendanceDate string `json:"attendance_date"`
	StartMinute    int64  `json:"start_minute"`
	EndMinute      int64  `json:"end_minute"`
	CreatedAtUtc   int64  `json:"created_at_utc"`
	UpdatedAtUtc   int64  `json:"updated_at_utc"`
}

type MemberSession struct {
	ID           int64  `json:"id"`
	AccountID    int64  `json:"account_id"`
	TokenHash    []byte `json:"token_hash"`
	CsrfSecret   []byte `json:"csrf_secret"`
	CreatedAtUtc int64  `json:"created_at_utc"`
	ExpiresAtUtc int64  `json:"expires_at_utc"`
}

type OneOffEvent struct {
	ID          int64  `json:"id"`
	EventDate   string `json:"event_date"`
	Court       int64  `json:"court"`
	Kind        string `json:"kind"`
	Title       string `json:"title"`
	StartMinute int64  `json:"start_minute"`
	EndMinute   int64  `json:"end_minute"`
}

type RecoveryMetadatum struct {
	Singleton                  int64  `json:"singleton"`
	RecoveryGeneration         string `json:"recovery_generation"`
	RecoveryLockdown           int64  `json:"recovery_lockdown"`
	AdminCredentialFingerprint string `json:"admin_credential_fingerprint"`
}

type ScheduleException struct {
	ID                     int64          `json:"id"`
	WeeklySeriesID         int64          `json:"weekly_series_id"`
	OccurrenceDate         string         `json:"occurrence_date"`
	Cancelled              int64          `json:"cancelled"`
	ReplacementCourt       sql.NullInt64  `json:"replacement_court"`
	ReplacementKind        sql.NullString `json:"replacement_kind"`
	ReplacementStartMinute sql.NullInt64  `json:"replacement_start_minute"`
	ReplacementEndMinute   sql.NullInt64  `json:"replacement_end_minute"`
}

type SocialSession struct {
	ID                 int64          `json:"id"`
	IsoWeekday         int64          `json:"iso_weekday"`
	StartMinute        int64          `json:"start_minute"`
	EndMinute          int64          `json:"end_minute"`
	EffectiveStartDate string         `json:"effective_start_date"`
	EffectiveEndDate   sql.NullString `json:"effective_end_date"`
}

type SyntheticFixtureMetadatum struct {
	Singleton     int64  `json:"singleton"`
	LoadedForDate string `json:"loaded_for_date"`
}

type WeeklySeries struct {
	ID                 int64          `json:"id"`
	Court              int64          `json:"court"`
	Kind               string         `json:"kind"`
	Title              string         `json:"title"`
	IsoWeekday         int64          `json:"iso_weekday"`
	StartMinute        int64          `json:"start_minute"`
	EndMinute          int64          `json:"end_minute"`
	EffectiveStartDate string         `json:"effective_start_date"`
	EffectiveEndDate   sql.NullString `json:"effective_end_date"`
}
