// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const countAccounts = `-- name: CountAccounts :one
SELECT count(*) FROM accounts
`

// CountAccounts
//
//	SELECT count(*) FROM accounts
func (q *Queries) CountAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRecoveryMetadata = `-- name: GetRecoveryMetadata :one
SELECT recovery_generation, recovery_lockdown, admin_credential_fingerprint
FROM recovery_metadata
WHERE singleton = 1
`

type GetRecoveryMetadataRow struct {
	RecoveryGeneration         string `json:"recovery_generation"`
	RecoveryLockdown           int64  `json:"recovery_lockdown"`
	AdminCredentialFingerprint string `json:"admin_credential_fingerprint"`
}

// GetRecoveryMetadata
//
//	SELECT recovery_generation, recovery_lockdown, admin_credential_fingerprint
//	FROM recovery_metadata
//	WHERE singleton = 1
func (q *Queries) GetRecoveryMetadata(ctx context.Context) (GetRecoveryMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, getRecoveryMetadata)
	var i GetRecoveryMetadataRow
	err := row.Scan(&i.RecoveryGeneration, &i.RecoveryLockdown, &i.AdminCredentialFingerprint)
	return i, err
}

const initializeRecoveryGeneration = `-- name: InitializeRecoveryGeneration :execrows
UPDATE recovery_metadata
SET recovery_generation = ?
WHERE singleton = 1 AND recovery_generation = '' AND recovery_lockdown = 0
`

// InitializeRecoveryGeneration
//
//	UPDATE recovery_metadata
//	SET recovery_generation = ?
//	WHERE singleton = 1 AND recovery_generation = '' AND recovery_lockdown = 0
func (q *Queries) InitializeRecoveryGeneration(ctx context.Context, recoveryGeneration string) (int64, error) {
	result, err := q.db.ExecContext(ctx, initializeRecoveryGeneration, recoveryGeneration)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAnonymousAttendanceIntervals = `-- name: ListAnonymousAttendanceIntervals :many
SELECT attendance_date, start_minute, end_minute
FROM attendance_plans
WHERE attendance_date BETWEEN ?1 AND ?2
ORDER BY attendance_date, start_minute, end_minute
`

type ListAnonymousAttendanceIntervalsParams struct {
	FromDate    string `json:"from_date"`
	ThroughDate string `json:"through_date"`
}

type ListAnonymousAttendanceIntervalsRow struct {
	AttendanceDate string `json:"attendance_date"`
	StartMinute    int64  `json:"start_minute"`
	EndMinute      int64  `json:"end_minute"`
}

// ListAnonymousAttendanceIntervals
//
//	SELECT attendance_date, start_minute, end_minute
//	FROM attendance_plans
//	WHERE attendance_date BETWEEN ?1 AND ?2
//	ORDER BY attendance_date, start_minute, end_minute
func (q *Queries) ListAnonymousAttendanceIntervals(ctx context.Context, arg ListAnonymousAttendanceIntervalsParams) ([]ListAnonymousAttendanceIntervalsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAnonymousAttendanceIntervals, arg.FromDate, arg.ThroughDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnonymousAttendanceIntervalsRow{}
	for rows.Next() {
		var i ListAnonymousAttendanceIntervalsRow
		if err := rows.Scan(&i.AttendanceDate, &i.StartMinute, &i.EndMinute); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOneOffEvents = `-- name: ListOneOffEvents :many
SELECT id, event_date, court, kind, title, start_minute, end_minute
FROM one_off_events
WHERE event_date BETWEEN ?1 AND ?2
ORDER BY event_date, start_minute, court, id
`

type ListOneOffEventsParams struct {
	FromDate    string `json:"from_date"`
	ThroughDate string `json:"through_date"`
}

// ListOneOffEvents
//
//	SELECT id, event_date, court, kind, title, start_minute, end_minute
//	FROM one_off_events
//	WHERE event_date BETWEEN ?1 AND ?2
//	ORDER BY event_date, start_minute, court, id
func (q *Queries) ListOneOffEvents(ctx context.Context, arg ListOneOffEventsParams) ([]OneOffEvent, error) {
	rows, err := q.db.QueryContext(ctx, listOneOffEvents, arg.FromDate, arg.ThroughDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OneOffEvent{}
	for rows.Next() {
		var i OneOffEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventDate,
			&i.Court,
			&i.Kind,
			&i.Title,
			&i.StartMinute,
			&i.EndMinute,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSocialSessions = `-- name: ListSocialSessions :many
SELECT id, iso_weekday, start_minute, end_minute, effective_start_date, effective_end_date
FROM social_sessions
WHERE effective_start_date <= ?1
  AND (effective_end_date IS NULL OR effective_end_date >= ?2)
ORDER BY iso_weekday, start_minute, id
`

type ListSocialSessionsParams struct {
	ThroughDate string         `json:"through_date"`
	FromDate    sql.NullString `json:"from_date"`
}

// ListSocialSessions
//
//	SELECT id, iso_weekday, start_minute, end_minute, effective_start_date, effective_end_date
//	FROM social_sessions
//	WHERE effective_start_date <= ?1
//	  AND (effective_end_date IS NULL OR effective_end_date >= ?2)
//	ORDER BY iso_weekday, start_minute, id
func (q *Queries) ListSocialSessions(ctx context.Context, arg ListSocialSessionsParams) ([]SocialSession, error) {
	rows, err := q.db.QueryContext(ctx, listSocialSessions, arg.ThroughDate, arg.FromDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SocialSession{}
	for rows.Next() {
		var i SocialSession
		if err := rows.Scan(
			&i.ID,
			&i.IsoWeekday,
			&i.StartMinute,
			&i.EndMinute,
			&i.EffectiveStartDate,
			&i.EffectiveEndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeeklySeries = `-- name: ListWeeklySeries :many
SELECT id, court, kind, title, iso_weekday, start_minute, end_minute,
       effective_start_date, effective_end_date
FROM weekly_series
WHERE effective_start_date <= ?1
  AND (effective_end_date IS NULL OR effective_end_date >= ?2)
ORDER BY iso_weekday, start_minute, court, id
`

type ListWeeklySeriesParams struct {
	ThroughDate string         `json:"through_date"`
	FromDate    sql.NullString `json:"from_date"`
}

// ListWeeklySeries
//
//	SELECT id, court, kind, title, iso_weekday, start_minute, end_minute,
//	       effective_start_date, effective_end_date
//	FROM weekly_series
//	WHERE effective_start_date <= ?1
//	  AND (effective_end_date IS NULL OR effective_end_date >= ?2)
//	ORDER BY iso_weekday, start_minute, court, id
func (q *Queries) ListWeeklySeries(ctx context.Context, arg ListWeeklySeriesParams) ([]WeeklySeries, error) {
	rows, err := q.db.QueryContext(ctx, listWeeklySeries, arg.ThroughDate, arg.FromDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeeklySeries{}
	for rows.Next() {
		var i WeeklySeries
		if err := rows.Scan(
			&i.ID,
			&i.Court,
			&i.Kind,
			&i.Title,
			&i.IsoWeekday,
			&i.StartMinute,
			&i.EndMinute,
			&i.EffectiveStartDate,
			&i.EffectiveEndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
